ICM patch release r0.2.1
camaraproject/IdentityAndConsentManagement pull request #202
Opened 2024-09-16 15:26 UTC by jpengar

#### What type of PR is this?

* subproject management

#### What this PR does / why we need it:

This PR is to update the README and CHANGELOG files for the r0.2.1 patch release. This patch release fixes broken W3C Data Privacy Vocabulary (DPV) reference links in the ICM documentation.
The original idea was to create a maintenance release (and maintenance branch) where this needed fix would be applied. However, there are still some pending discussions about maintenance releases in the Release Management Working Group, and as a short-term solution it was suggested by @hdamker (https://github.com/camaraproject/IdentityAndConsentManagement/pull/196#issuecomment-2343801035) to create a patch release in the `main` branch.

#### Which issue(s) this PR fixes:

N/A (It is related to Issue #195 and the fix applied in PR #196)

#### Special notes for reviewers:

See #196 for further context.

#### Changelog input

```
 ICM patch release r0.2.1
```

#### Additional documentation 

https://github.com/camaraproject/ReleaseManagement/issues/93

2024-09-19 13:01 UTC, AxelNennker approved these changes

2024-09-24 17:04 UTC, tanjadegroot requested changes

2024-09-24 17:04 UTC, tanjadegroot commented on README.md
the link to meeting minutes needs to be update to point to the new cloud wiki

any links to Concfluence in the repo need to updated to their cloud wiki equivalent :-(

2024-09-25 08:47 UTC, jpengar commented on README.md
I will take a look to see if it can be easily fixed, but this PR is not intended to fix that though...

2024-09-25 08:48 UTC, jpengar commented on README.md
> +* `NEW`: Release 0.2.0 of the "Identity and Consent Management" guidelines and documentation for the CAMARA APIs is available under the tag [r0.2.1](https://github.com/camaraproject/IdentityAndConsen
Ups, I'll fix it

2024-09-25 08:49 UTC, jpengar commented on README.md
I can try to use this PR to fix that as well, let me check.

2024-09-25 16:01 UTC, jpengar commented on README.md
Fixed in https://github.com/camaraproject/IdentityAndConsentManagement/pull/202/commits/9d8623c93aac156fca857d0fa2a7fdc263f3081c

2024-09-25 16:02 UTC, jpengar commented on README.md
> +* `NEW`: Release 0.2.0 of the "Identity and Consent Management" guidelines and documentation for the CAMARA APIs is available under the tag [r0.2.1](https://github.com/camaraproject/IdentityAndConsen
Fixed in https://github.com/camaraproject/IdentityAndConsentManagement/pull/202/commits/9d8623c93aac156fca857d0fa2a7fdc263f3081c

2024-09-25 16:03 UTC, jpengar commented on README.md
I've updated the terminology to be telco agnostic and more generic (the README doesn't need to be more specific). Take a look at the commit  https://github.com/camaraproject/IdentityAndConsentManagement/pull/202/commits/9d8623c93aac156fca857d0fa2a7fdc263f3081c

2024-09-25 16:04 UTC, jpengar commented on README.md
> +* `NEW`: Release 0.2.0 of the "Identity and Consent Management" guidelines and documentation for the CAMARA APIs is available under the tag [r0.2.1](https://github.com/camaraproject/IdentityAndConsen
Fixed in https://github.com/camaraproject/IdentityAndConsentManagement/pull/202/commits/9d8623c93aac156fca857d0fa2a7fdc263f3081c

2024-09-26 17:20 UTC, tanjadegroot approved these changes

2024-09-26 17:37 UTC, tanjadegroot commented
as I put here as well (https://github.com/camaraproject/IdentityAndConsentManagement/pull/196#issuecomment-2377510247):

For maintenance releases of APIs, the process is described here: https://lf-camaraproject.atlassian.net/wiki/spaces/CAM/pages/14559630/API+Release+Process#PATCH-update.

We could add something similar to the Comm/ICM process part (with the exception that it would use the version number iso the release nr for Fall24 patches.).

So the process would mean to have a branch called "maintenance-020" of the 0.2.0 release in which the above changes will be applied.
On that branch you would then have the patch releases of 0.2.1, 0.2.2, or r1.3 if we consider the current release did r1.1 (RC) and r1.2 (currrent public) applying the release numbering to Comm/ICM as well. In that case the patch should include the version file in the main directory VERSION.MD with inside the text "icm-version: 0.2.1" for this first patch.

for me these changes can either
1) go in and later changes could be done a additional maintenance-releases on this branch as needed, 
2)  or be released later 

but as this fixed broken links etc, I would consider option 1 is best.

Each patch that is released, if no impact on API implementation can also be merged into main immediately IMHO.


/LGTM from Release Management

2024-09-27 09:29 UTC, hdamker commented
@tanjadegroot 
> 
> For maintenance releases of APIs, the process is described here: https://lf-camaraproject.atlassian.net/wiki/spaces/CAM/pages/14559630/API+Release+Process#PATCH-update.
> 
I'm not sure that this part of the release management processes was already reviewed in detail. I have added some comments there. Especially I don't see why we need to create already a maintenance branch if there were no other changes in main since the Meta-release public release.

> We could add something similar to the Comm/ICM process part (with the exception that it would use the version number iso the release nr for Fall24 patches.).
> 

> So the process would mean to have a branch called "maintenance-020" of the 0.2.0 release in which the above changes will be applied. On that branch you would then have the patch releases of 0.2.1, 0.2.2, or r1.3 if we consider the current release did r1.1 (RC) and r1.2 (currrent public) applying the release numbering to Comm/ICM as well. In that case the patch should include the version file in the main directory VERSION.MD with inside the text "icm-version: 0.2.1" for this first patch.
> 
I wouldn't do the change of release numbering now in context of the Fall24 release ... we can't change the existing releases, so I would propose to start the new numbering only with the Spring25 

> ...

> /LGTM from Release Management

For this Patch and the PR same from my perspective: /LGTM

2024-09-27 09:35 UTC, jpengar commented
@tanjadegroot @hdamker If you don't mind, I will merge this PR and generate the new patch release as suggested as a short-term solution. And then for future changes (hopefully not needed for this release) we can follow whatever procedure we end up agreeing on in the Release Management WG.
CC @AxelNennker @sebdewet

2024-10-01 13:21 UTC, tanjadegroot commented
@jpengar OK for the short terms solution LGTM

2024-10-01 13:30 UTC, tanjadegroot commented
@hdamker 

> > For maintenance releases of APIs, the process is described here: https://lf-camaraproject.atlassian.net/wiki/spaces/CAM/pages/14559630/API+Release+Process#PATCH-update.
> 
> I'm not sure that this part of the release management processes was already reviewed in detail. I have added some comments there. 

true, not actively, we are improving the text as we learn.

> Especially I don't see why we need to create already a maintenance branch if there were no other changes in main since the Meta-release public release.

IMHO the maintenance release branch approach should be the standard process, but if you want to skip it this first time, it is OK but as an exception.

> 
> > We could add something similar to the Comm/ICM process part (with the exception that it would use the version number iso the release nr for Fall24 patches.).
> 
> > So the process would mean to have a branch called "maintenance-020" of the 0.2.0 release in which the above changes will be applied. On that branch you would then have the patch releases of 0.2.1, 0.2.2, or r1.3 if we consider the current release did r1.1 (RC) and r1.2 (currrent public) applying the release numbering to Comm/ICM as well. In that case the patch should include the version file in the main directory VERSION.MD with inside the text "icm-version: 0.2.1" for this first patch.

Following one of your comments the name of the maintenance branch should exclude the partch number ("z" in "x.y.z") do maintenance-02.

> I wouldn't do the change of release numbering now in context of the Fall24 release ... we can't change the existing releases, so I would propose to start the new numbering only with the Spring25

OK, agree

2024-10-01 16:02 UTC, hdamker approved these changes
LGTM from perspective of release management and can be merged, and the release created.

2024-10-01 16:51 UTC, diegogonmar commented
@AxelNennker @sebdewet, as Jesús is on holiday, can you proceed with merge? And then create the release and release tag and update the RM confluence Fall24 page with the new patch release info.? Thanks!

2024-10-02 06:58 UTC, AxelNennker approved these changes

2024-10-02 07:01 UTC, merged